### ISSUE TITLE
java.lang.IllegalAccessError: superclass access check failed: class de.qtc.rmg.io.MaliciousOutputStream

### ISSUE THREAD

**Issue by superhac** [qtc-de/remote-method-guesser#40] opened 2022-12-27 18:14 UTC
Hi,

I've tried both the compiling and the compiled release version, and still getting the following stack trace regardless of the command options.  Any idea?

`$./rmg-4.3.1-jar-with-dependencies.jar scan 10.24.1.11
[+] Scanning 112 Ports on 10.24.1.11 for RMI services.
[+]
[-] 	Internal error. Caught unexpected java.lang.reflect.InvocationTargetException within the Operation.invoke(...) function.
[-] 	StackTrace:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at de.qtc.rmg.operations.Operation.invoke(Operation.java:325)
	at de.qtc.rmg.Starter.main(Starter.java:26)
Caused by: java.lang.IllegalAccessError: superclass access check failed: class de.qtc.rmg.io.MaliciousOutputStream (in unnamed module @0x2f4551e6) cannot access class sun.rmi.server.MarshalOutputStream (in module java.rmi) because module java.rmi does not export sun.rmi.server to unnamed module @0x2f4551e6
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at de.qtc.rmg.operations.PortScanner$PortScanWorker.<init>(PortScanner.java:153)
	at de.qtc.rmg.operations.PortScanner.portScan(PortScanner.java:95)
	at de.qtc.rmg.operations.Dispatcher.dispatchPortScan(Dispatcher.java:608)
	... 6 more
[-] 	Cannot continue from here.`

**Comment by psyray** [comment] 2022-12-31 00:19
Same stack trace for me, tried 4.3.0, same problem

```java
java -jar rmg-4.3.1-jar-with-dependencies.jar scan 10.11.1.73     
[+] Scanning 112 Ports on 10.11.1.73 for RMI services.
[+]
[-] 	Internal error. Caught unexpected java.lang.reflect.InvocationTargetException within the Operation.invoke(...) function.
[-] 	StackTrace:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at de.qtc.rmg.operations.Operation.invoke(Operation.java:325)
	at de.qtc.rmg.Starter.main(Starter.java:26)
Caused by: java.lang.IllegalAccessError: superclass access check failed: class de.qtc.rmg.io.MaliciousOutputStream (in unnamed module @0x2f4551e6) cannot access class sun.rmi.server.MarshalOutputStream (in module java.rmi) because module java.rmi does not export sun.rmi.server to unnamed module @0x2f4551e6
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at de.qtc.rmg.operations.PortScanner$PortScanWorker.<init>(PortScanner.java:153)
	at de.qtc.rmg.operations.PortScanner.portScan(PortScanner.java:95)
	at de.qtc.rmg.operations.Dispatcher.dispatchPortScan(Dispatcher.java:608)
	... 6 more
[-] 	Cannot continue from here.
```

JAVA version
```java
java --version                                                     
openjdk 17.0.4 2022-07-19
OpenJDK Runtime Environment (build 17.0.4+8-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 17.0.4+8-Debian-1deb11u1, mixed mode, sharing
```

**Comment by qtc-de** [comment] 2022-12-31 08:53
Hi @superhac,

as correctly analyzed by @psyray, the issue comes from the *Java* version you are using. *remote-method-guesser* is accessing internal *Java APIs* that are normally not exported and should not be used by production applications. Older *Java* versions only create a warning during compile time for this situation. This warning already mentions that such access to internal APIs will be blocked in future versions.

The easiest way for resolving the issue is to use an older *Java* version like *jdk8* or *jdk11*. It is also possible to export the required modules manually in the command line when using newer *Java* versions. If I recall correctly, there is an `--add-exports` option to achieve this. However, I have to investigate which options are exactly required to get it running. I will evaluate this and add it to the documentation. Once it is added, I will update the issue. Please keep it open until this point :)

Thanks for reporting :+1:

**Comment by psyray** [comment] 2022-12-31 12:28
> The easiest way for resolving the issue is to use an older Java version like jdk8 or jdk11
And the easiest way to have multiple java version on your computer is the awesome SDKMan !
https://sdkman.io/

```sh
 curl -s "https://get.sdkman.io" | bash 
sdk install java 11.0.14-tem
sdk use java 11.0.14-tem
```

**Comment by calex80** [comment] 2023-01-13 16:36
I have downgraded to java 11 and it works.
Here a link how to proceed to... https://computingforgeeks.com/how-to-set-default-java-version-on-ubuntu-debian/

**Closed** 2023-01-19 21:14 UTC
Labels: documentation

**Comment by qtc-de** [comment] 2023-01-19 21:24
As it turns out, the required `--add-opens` specifications for *Java16+* can also be specified within the Jar Manifest. From version `v4.4.0` on, *remote-method-guesser* includes the corresponding options and should be *Java16+* compatible without requiring additional command line arguments :smile:
